development:
  adapter: postgresql
  encoding: unicode
  database: diploma_development
  pool: 5
  username: anton
  password: Iamaprogrammer

test:
  adapter: postgresql
  encoding: unicode
  database: diploma_test
  pool: 5
  username: anton
  password: Iamaprogrammer
